services:
  spark:
    image: apache/spark:3.5.1
    container_name: spark
    user: root
    volumes:
      - ../spark-mnt:/opt/spark-mnt
    ports:
      - 8888:8888
      - 18080:8080
      - 10000:10000
      - 10001:10001
    command: >
      /bin/bash -c "mkdir -p /home/spark/.ivy2/cache && tail -f /dev/null"
